/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'roy' at '2/28/16 6:41 PM' with Gradle 2.11
 *
 * @author roy, @date 2/28/16 6:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
